const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const KEY='dfDialV10'; let view='home', beanTab='current', maintTab='grinder', selectedMethod='Espresso';
const iso=()=>new Date().toISOString(), today=()=>new Date().toISOString().slice(0,10);
const brewMethods=['Espresso','Pour Over','AeroPress','French Press','Moka Pot','Other'];
const models=['DF54','DF64','DF64V','DF83','DF83V'];
let timer={running:false,start:0,elapsed:0,int:null};
const h=(ms=12)=>{try{navigator.vibrate&&navigator.vibrate(ms)}catch(e){}};
const esc=(s='')=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function seed(){let g=uid(), b1=uid(), b2=uid(), p1=uid(), p2=uid(), p3=uid(), now=iso(); return {
 currentBeanId:b1,
 userProfile:{brew:['Espresso','Pour Over'],machine:{manufacturer:'ECM',model:'Synchronika II'},grinders:[{id:g,model:'DF64',name:'DF64 Gen 2',burrType:'Stainless Steel',burrOther:'',profile:'Multipurpose (espresso)'}],flavour:{roast:52,notes:['Chocolate','Sweet']},workflow:['WDT','RDT','Slow feed']},
 beans:[
  {id:b1,status:'current',name:'Brazil Fazenda Ambiental',roaster:'Archive Coffee',origin:'Brazil',process:'Natural',roastLevel:'Medium',roastDate:'2026-05-18',photo:'',brewProfiles:{Espresso:[{id:p1,name:'Current',active:true,createdAt:now,score:8.2,grinderId:g,grind:18.6,dose:18,yieldOut:36,time:29,ratio:'1:2.0',notes:'Sweet, clean, dialed in.'},{id:p2,name:'Turbo Shot',active:false,createdAt:now,score:7.9,grinderId:g,grind:20.4,dose:18,yieldOut:54,time:24,ratio:'1:3.0',notes:''}], 'Pour Over':[{id:p3,name:'Current',active:true,createdAt:now,score:8.6,grinderId:g,grind:42,dose:20,water:320,bloom:45,totalTime:195,notes:'Balanced sweetness.'}] }},
  {id:b2,status:'current',name:'Ethiopia Chelbesa',roaster:'Konga',origin:'Ethiopia',process:'Washed',roastLevel:'Light',roastDate:'2026-05-24',photo:'',brewProfiles:{Espresso:[{id:uid(),name:'Current',active:true,createdAt:now,score:8.0,grinderId:g,grind:17.8,dose:18,yieldOut:38,time:31,ratio:'1:2.1',notes:'Floral, sweet.'}]}}
 ],
 brews:[{id:uid(),beanId:b1,method:'Espresso',profileId:p1,grinderId:g,grind:18.6,dose:18,yieldOut:36.2,time:29.4,rating:8.2,flavours:['Chocolate','Sweet'],notes:'Balanced and sweet.',createdAt:now},{id:uid(),beanId:b1,method:'Pour Over',profileId:p3,grinderId:g,grind:42,dose:20,water:320,totalTime:195,bloom:45,rating:8.6,flavours:['Sweet'],notes:'Good clarity.',createdAt:now},{id:uid(),beanId:b2,method:'Espresso',grinderId:g,grind:17.8,dose:18,yieldOut:38,time:31,rating:8.0,flavours:['Floral'],notes:'Bright.',createdAt:now}],
 maintenance:[{id:uid(),group:'grinder',name:'Grinder deep clean',item:'DF grinder',intervalDays:45,lastDone:today()},{id:uid(),group:'grinder',name:'Chute cleaning',item:'DF grinder',intervalDays:7,lastDone:today()},{id:uid(),group:'espresso',name:'Backflushing',item:'Espresso machine',intervalDays:7,lastDone:today()}],
 settings:{rateReminder:true,rateDelay:7}
}}
function migrate(o){let f=seed(); if(!o)return f; o.userProfile=o.userProfile||o.profile||f.userProfile; o.settings=o.settings||f.settings; o.maintenance=o.maintenance||f.maintenance; o.beans=(o.beans||f.beans).map(b=>({...b,status:b.status==='archived'?'archived':'current',photo:b.photo||'',brewProfiles:b.brewProfiles||{Espresso:[]}})); o.brews=o.brews||o.shots||f.brews; o.currentBeanId=o.currentBeanId||o.beans[0]?.id; ['Grinder deep clean','Chute cleaning','Backflushing'].forEach((n,i)=>{if(!o.maintenance.some(m=>m.name===n))o.maintenance.push(f.maintenance[i])}); return o}
function load(){try{let s=localStorage.getItem(KEY)||localStorage.getItem('dfDialV9')||localStorage.getItem('dfDialV8'); if(s)return migrate(JSON.parse(s))}catch(e){} return seed()} let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const bean=id=>state.beans.find(b=>b.id===id), currentBean=()=>bean(state.currentBeanId)||state.beans.find(b=>b.status==='current')||state.beans[0];
const grinder=id=>(state.userProfile.grinders||[]).find(g=>g.id===id)||state.userProfile.grinders?.[0]||{};
const brewsFor=(id,method)=>state.brews.filter(x=>x.beanId===id&&(!method||x.method===method)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
const lastBrew=(id,method)=>brewsFor(id,method)[0];
function ratio(x){let d=+x.dose, y=+(x.yieldOut||x.water); return d&&y?'1:'+(y/d).toFixed(1):'—'}
function fmt(sec){sec=+(sec||0); if(sec<60)return sec.toFixed(1).padStart(4,'0'); let m=Math.floor(sec/60), r=(sec%60).toFixed(1).padStart(4,'0'); return `${m}:${r}`}
function dateShort(s){return new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function toast(m){let t=$('#toast'); t.textContent=m; t.style.display='block'; clearTimeout(t._t); t._t=setTimeout(()=>t.style.display='none',1800)}
function dueInfo(){let x=null; state.maintenance.forEach(m=>{let d=new Date(m.lastDone); d.setDate(d.getDate()+Number(m.intervalDays)); if(!x||d<x.date)x={m,date:d}}); return {x,days:x?Math.ceil((x.date-new Date())/86400000):0}}
function logo(){return `<div class="hero"><img src="dfgrinderslogo.png" class="wordmark"></div>`}
function icon(name){const path={home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z',beans:'M15.6 3.2c3.2 1.2 4.7 5.8 3.3 10.2s-5.1 7-8.3 5.8S5.9 13.4 7.3 9 12.4 2 15.6 3.2Z M8.2 18.5c2.4-2.5 4.1-5.3 5.2-8.5.7-2.1 1.1-4.1 1.2-6',shot:'M6 8h12v5.5a6 6 0 0 1-12 0z M18 10h2.2a2.3 2.3 0 0 1 0 4.6H18 M8 20h8 M10 4h4',maint:'M14.8 6.1a4.5 4.5 0 0 0-5.4 5.4l-5.9 5.9 3.1 3.1 5.9-5.9a4.5 4.5 0 0 0 5.4-5.4l-3 3-2.1-2.1z',more:'M4 7h16 M4 12h16 M4 17h16',pencil:'M4 20h4l11-11-4-4L4 16z M13 6l4 4',back:'M15 18l-6-6 6-6',camera:'M4 8h3l1.5-2h7L17 8h3v11H4z M12 11a3 3 0 1 0 0 6 3 3 0 0 0 0-6z'}[name]; return `<svg viewBox="0 0 24 24"><path d="${path}"/></svg>`}
function brewSvg(m){let d={Espresso:'M6 8h10v5a5 5 0 0 1-10 0z M16 10h2a2 2 0 1 1 0 4h-2 M8 20h6', 'Pour Over':'M7 7h10l-2 7H9z M9 14h6 M12 3v4 M5 20h14', AeroPress:'M8 4h8v14H8z M6 20h12 M10 7h4', 'French Press':'M7 6h10v12H7z M9 4h6 M12 4v4 M6 20h12', 'Moka Pot':'M8 9h8l2 9H6z M9 9l1-5h4l1 5 M8 13h8', Other:'M12 5v14 M5 12h14'}[m]||'M12 5v14 M5 12h14'; return `<svg viewBox="0 0 24 24"><path d="${d}"/></svg>`}
function nav(){return `<nav class="nav"><button class="${view==='home'?'active':''}" onclick="go('home')">${icon('home')}</button><button class="${view==='beans'?'active':''}" onclick="go('beans')">${icon('beans')}</button><button class="plus" onclick="go('log')">+</button><button class="${view==='maintenance'?'active':''}" onclick="go('maintenance')">${icon('maint')}</button><button class="${view==='more'?'active':''}" onclick="go('more')">${icon('more')}</button></nav>`}
function go(v){stopTimer(false); view=v; render()}
function render(){save(); $('#app').innerHTML=`<div class="wrap">${logo()}${views[view]?views[view]():views.home()}${nav()}</div>`; bind()}
const views={
 home(){let b=currentBean(), l=b&&lastBrew(b.id), g=grinder(l?.grinderId||b?.grinderId), d=dueInfo(), month=new Date().toISOString().slice(0,7); return `${profileCard()}<section class="card click" onclick="openBeanDetail('${b?.id||''}')"><h2>Current Bean</h2>${beanMini(b,true)}</section><section class="card click" onclick="openBeanDetail('${b?.id||''}')"><h2>Last Used Settings</h2><div class="settings-summary"><div><b>${esc(g.name||g.model||'—')}</b><p>${esc([g.burrType==='Other'?g.burrOther:g.burrType,g.profile].filter(Boolean).join(' • '))}</p></div><strong>${l?l.grind:'—'}</strong></div><div class="metric-grid"><p>Dose<br><b>${l?.dose||'—'}g</b></p><p>Output<br><b>${l?.yieldOut||l?.water||'—'}g</b></p><p>Ratio<br><b>${l?ratio(l):'—'}</b></p><p>Time<br><b>${l?fmt(l.time||l.totalTime):'—'}s</b></p></div></section><div class="stats"><button onclick="go('beans')"><span>Current Beans</span><b>${state.beans.filter(x=>x.status==='current').length}</b></button><button onclick="go('history')"><span>Shots This Month</span><b>${state.brews.filter(x=>x.createdAt.slice(0,7)===month).length}</b></button><button onclick="go('maintenance')"><span>Maintenance Due</span><b>${d.days<=0?'Now':d.days+'d'}</b></button></div><section class="card click" onclick="go('history')"><h2>Shot History</h2>${state.brews.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,3).map(brewRow).join('')||'<p>No brews yet.</p>'}</section>`},
 beans(){let arch=beanTab==='archive', list=state.beans.filter(b=>arch?b.status==='archived':b.status==='current'); return `<section class="card"><h2>Beans</h2><div class="tabs"><button class="${!arch?'sel':''}" onclick="beanTab='current';render()">Current <span>${state.beans.filter(x=>x.status==='current').length}</span></button><button class="${arch?'sel':''}" onclick="beanTab='archive';render()">Archive <span>${state.beans.filter(x=>x.status==='archived').length}</span></button></div><input placeholder="Search ${arch?'archive':'current'} beans" oninput="filterBeans(this.value)"><button class="btn secondary" onclick="openBeanForm()">Add Bean</button><div id="beanList">${list.map(beanCard).join('')||'<p>No beans here.</p>'}</div></section>`},
 history(){return `<section class="card"><h2>Last 20 Brews</h2>${state.brews.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,20).map(brewRow).join('')||'<p>No brews yet.</p>'}</section>`},
 log(){return logView()},
 maintenance(){return maintView()},
 more(){return `<section class="card"><h2>Settings</h2><div class="tile ${state.settings.rateReminder?'selected':''}" onclick="state.settings.rateReminder=!state.settings.rateReminder;render()"><b>Ask me to rate my brew later</b><p>${state.settings.rateReminder?'Enabled':'Disabled'}</p></div><label>Rating reminder delay</label><select onchange="state.settings.rateDelay=this.value;save()"><option value="5" ${state.settings.rateDelay==5?'selected':''}>5 minutes</option><option value="10" ${state.settings.rateDelay==10?'selected':''}>10 minutes</option></select><button class="btn full secondary" onclick="exportData()">Export Backup</button><button class="btn full secondary" onclick="localStorage.removeItem(KEY);location.reload()">Reset Demo Data</button></section>`}
};
function profileCard(){let p=state.userProfile,g=p.grinders[0]||{}; return `<section class="card profile-card"><button class="edit-icon" onclick="editProfile()">${icon('pencil')}</button><h2>Profile</h2><div class="method-row">${(p.brew||[]).map(m=>`<span>${brewSvg(m)}</span>`).join('')}</div><div class="detail compact"><div><span>Machine</span>${esc([p.machine.manufacturer,p.machine.model].filter(Boolean).join(' ')||'Not set')}</div><div><span>Grinder</span>${esc([g.model,g.burrType==='Other'?g.burrOther:g.burrType,g.profile].filter(Boolean).join(' • '))}</div><div><span>Preference</span>${p.flavour.roast<35?'Darker':p.flavour.roast>65?'Lighter':'Medium'} • ${(p.flavour.notes||[]).join(', ')}</div><div><span>Workflow</span>${(p.workflow||[]).join(', ')||'Not set'}</div></div></section>`}
function beanMini(b,big=false){if(!b)return '<p>No bean selected.</p>';return `<div class="bean-card"><div class="bag ${b.photo?'has-photo':''}">${b.photo?`<img src="${b.photo}">`:'DF'}</div><div><div class="bean-title">${esc(b.name)}</div><p>${esc(b.roaster)}<br>${esc([b.origin,b.process].filter(Boolean).join(' • '))}</p></div><span class="pill">${esc(b.roastLevel)}</span></div>`}
function beanCard(b){let l=lastBrew(b.id);return `<div class="bean-card click" onclick="openBeanDetail('${b.id}')"><div class="bag ${b.photo?'has-photo':''}">${b.photo?`<img src="${b.photo}">`:'DF'}</div><div><div class="bean-title">${esc(b.name)}</div><p>${esc(b.roaster)}<br>${esc(b.origin)} · ${l?l.grind+' setting':'No brews yet'}</p></div><span class="pill">${esc(b.roastLevel)}</span></div>`}
function methodTabs(b,sel){let methods=[...new Set([...brewMethods,...Object.keys(b.brewProfiles||{})])].filter(m=>m==='Other'||(b.brewProfiles?.[m]?.length)||brewMethods.includes(m));return `<div class="brew-tabs">${methods.map(m=>`<button class="${sel===m?'sel':''}" onclick="selectedMethod='${m}';openBeanDetail('${b.id}',false)">${brewSvg(m)}<small>${m}</small></button>`).join('')}</div>`}
function activeProfile(b,m){let arr=b.brewProfiles?.[m]||[]; return arr.find(p=>p.active)||arr[0]}
function openBeanDetail(id,modalOpen=true){let b=bean(id); if(!b)return; if(!b.brewProfiles)b.brewProfiles={}; if(!b.brewProfiles[selectedMethod])selectedMethod=Object.keys(b.brewProfiles)[0]||'Espresso'; let p=activeProfile(b,selectedMethod), g=grinder(p?.grinderId||b.grinderId), recent=brewsFor(b.id,selectedMethod).slice(0,3); let html=`<button class="back" onclick="closeModal()">${icon('back')}</button><button class="edit-icon modal-edit" onclick="openBeanForm('${b.id}')">${icon('pencil')}</button><div class="bean-hero"><button class="bag large ${b.photo?'has-photo':''}" onclick="pickPhoto('${b.id}')">${b.photo?`<img src="${b.photo}">`:'DF'}<em>${icon('camera')}</em></button><div><h1>${esc(b.name)}</h1><p>${esc([b.process,b.origin].filter(Boolean).join(' • '))}</p><span class="pill green">${b.status==='current'?'Current Bean':'Archived'}</span></div></div><h3>Brew Profiles</h3>${methodTabs(b,selectedMethod)}${profilePanel(b,selectedMethod,p,g)}<section class="inner-card"><h3>Equipment</h3><div class="equipment"><div>${brewSvg('Other')}<b>${esc(g.name||g.model||'—')}</b><small>${esc([g.burrType==='Other'?g.burrOther:g.burrType,g.profile].filter(Boolean).join(' • '))}</small></div><div>${brewSvg('Espresso')}<b>${esc([state.userProfile.machine.manufacturer,state.userProfile.machine.model].filter(Boolean).join(' ')||'Machine not set')}</b><small>Espresso Machine</small></div></div></section><section class="inner-card"><h3>Last 3 Brews <button onclick="showBeanHistory('${b.id}','${selectedMethod}')">View All (20)</button></h3><div class="mini-brews">${recent.map(x=>`<button onclick="brewDetail('${x.id}')"><small>${dateShort(x.createdAt)}</small><b>${x.rating||'—'}</b><span>${fmt(x.time||x.totalTime)}s</span></button>`).join('')||'<p>No brews yet.</p>'}</div></section><section class="inner-card"><h3>Saved Profiles (${selectedMethod}) <button onclick="manageProfiles('${b.id}','${selectedMethod}')">Manage</button></h3><div class="saved-profiles">${(b.brewProfiles[selectedMethod]||[]).map(pr=>`<button class="${pr.active?'sel':''}" onclick="profileDetail('${b.id}','${selectedMethod}','${pr.id}')"><b>${esc(pr.name)}</b><small>${dateShort(pr.createdAt)} · ${pr.score||'—'} Score</small></button>`).join('')}<button class="add" onclick="profileForm('${b.id}','${selectedMethod}')">+<small>Add New</small></button></div></section>`; if(modalOpen) modal(html); else {$('.modal').innerHTML=`<div class="modal-head"><span></span><button onclick="closeModal()">×</button></div>${html}`} }
function profilePanel(b,m,p,g){if(!p)return `<section class="profile-main"><h3>${m} — No Profile</h3><button class="btn full" onclick="profileForm('${b.id}','${m}')">Create ${m} Profile</button></section>`; let isEsp=m==='Espresso'; return `<section class="profile-main"><div class="profile-title"><h3>${m} — Current Profile</h3><span>Dialed In</span></div><div class="profile-grid"><div class="gauge"><b>${p.grind??'—'}</b><small>Grind Setting</small><em>${esc(g.name||g.model||'—')}</em></div><div class="recipe-list">${isEsp?`<p>☕ <b>${p.dose} g</b> Dose</p><p>☕ <b>${p.yieldOut} g</b> Yield</p><p>⏱ <b>${p.time} sec</b> Time</p><p>⟲ <b>${p.ratio||ratio(p)}</b> Ratio</p>`:`<p>☕ <b>${p.dose} g</b> Coffee</p><p>💧 <b>${p.water} g</b> Water</p><p>⏱ <b>${fmt(p.totalTime)}</b> Total</p>${m==='Pour Over'?`<p>◌ <b>${p.bloom||0} sec</b> Bloom</p>`:''}`}</div><div class="score"><b>${p.score||'—'}</b><small>Taste Score</small><span>★★★★★</span></div></div><button class="btn full" onclick="brewUsingProfile('${b.id}','${m}','${p.id}')">Brew Using This Profile</button></section>`}
function brewRow(x){let b=bean(x.beanId);return `<div class="shot-row click" onclick="brewDetail('${x.id}')"><b>${esc(b?.name||'Bean')}</b><span>${x.method}</span><strong>${x.rating||'—'}</strong><p>${esc([x.grind+' setting',fmt(x.time||x.totalTime)+'s',ratio(x)].join(' · '))}</p></div>`}
function showBeanHistory(id,m){modal(`<h2>${esc(bean(id)?.name||'')} — ${m}</h2>${brewsFor(id,m).slice(0,20).map(brewRow).join('')||'<p>No brews.</p>'}`)}
function brewDetail(id){let x=state.brews.find(b=>b.id===id), b=bean(x.beanId), g=grinder(x.grinderId); if(!x)return; modal(`<button class="edit-icon modal-edit" onclick="editBrew('${id}')">${icon('pencil')}</button><h2>${x.method} Details</h2><div class="hero-detail"><b>${x.rating||'—'}</b><span>Taste Score</span></div><div class="detail"><div><span>Bean</span>${esc(b?.name||'')}</div><div><span>Grinder</span>${esc(g.name||g.model||'—')}</div><div><span>Grind</span>${x.grind}</div><div><span>Dose</span>${x.dose}g</div><div><span>Output</span>${x.yieldOut||x.water||'—'}g</div><div><span>Ratio</span>${ratio(x)}</div><div><span>Time</span>${fmt(x.time||x.totalTime)}s</div><div><span>Flavours</span>${(x.flavours||[]).join(', ')||'—'}</div><div><span>Notes</span>${esc(x.notes||'—')}</div></div>`)}
function logView(pref={}){let b=bean(pref.beanId)||currentBean(); let m=pref.method||selectedMethod||'Espresso'; let p=pref.profileId?activeProfile(b,m):activeProfile(b,m); let g=grinder(p?.grinderId||b?.grinderId); return `<section class="card"><h2>Log Brew</h2><div class="seg"><button class="sel">Existing Bean</button><button onclick="openBeanForm()">New Bean</button></div><label>Bean</label><select id="logBean" onchange="state.currentBeanId=this.value;render()">${state.beans.filter(x=>x.status==='current').map(x=>`<option value="${x.id}" ${x.id===b?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><label>Brew Method</label><div class="brew-tabs compact">${brewMethods.map(x=>`<button class="${m===x?'sel':''}" onclick="selectedMethod='${x}';render()">${brewSvg(x)}<small>${x}</small></button>`).join('')}</div>${settingBlock(p?.grind||lastBrew(b?.id,m)?.grind||18.6)}<div class="metric-grid"><label>Dose<input id="dose" type="number" step="0.1" value="${p?.dose||18}"></label>${m==='Espresso'?`<label>Yield<input id="yieldOut" type="number" step="0.1" value="${p?.yieldOut||36}"></label>`:`<label>Water<input id="water" type="number" step="1" value="${p?.water||320}"></label>`}</div>${m==='Pour Over'?'<div class="metric-grid"><label>Bloom Timer<input id="bloom" type="number" value="45"></label><label>Total Brew Timer<input id="manualTime" type="number" step="0.1" placeholder="optional"></label></div>':''}${timerBlock()}${ratingBlock(7.5)}<label>Flavour Description</label><div class="select-grid">${['Chocolate','Fruity','Floral','Sweet','Funky'].map(x=>`<button type="button" class="tile small" data-flav="${x}" onclick="this.classList.toggle('selected')">${x}</button>`).join('')}</div><label>Flavour Notes</label><textarea id="notes" placeholder="Sweet, clean, slightly fast..."></textarea><button class="btn full" onclick="saveBrew('${b?.id||''}','${m}')">Save Brew</button><button class="btn secondary full" onclick="saveDialedProfile('${b?.id||''}','${m}')">Save Dialed-In Profile</button></section>`}
function settingBlock(v){return `<div class="setting-card"><div><label>Grinder</label><b>${esc(state.userProfile.grinders[0]?.name||state.userProfile.grinders[0]?.model||'DF Grinder')}</b></div><label class="setting-num">Setting<input id="grind" type="number" step="0.1" value="${(+v).toFixed(1)}" onchange="syncRuler(+this.value)"></label><div class="ruler" id="ruler"><div class="track" id="track"></div><div class="center-line"></div></div></div>`}
function timerBlock(){return `<div class="timer" id="timerCircle" onclick="toggleTimer()"><div class="timer-inner"><div><div class="timer-time" id="timeText">00.0</div><div class="timer-label" id="timeLabel">TAP TO START</div></div></div></div><button class="timer-button" id="timerBtn" onclick="event.stopPropagation();toggleTimer()"></button>`}
function ratingBlock(v=7.5){return `<label>Taste / Result</label><div class="rating-wrap"><div class="rating-num" id="ratingNum">${(+v).toFixed(1)}</div><input id="rating" class="rating-range" type="range" min="1" max="10" step="0.1" value="${v}" oninput="updateRating(this.value)"></div>`}
function updateRating(v){let n=$('#ratingNum'); if(!n)return; n.textContent=(+v).toFixed(1); let hue=+v<5?15:+v<7?45:115; n.style.color=`hsl(${hue},38%,68%)`}
function saveBrew(beanId,method){let elapsed=timer.elapsed/1000 || +($('#manualTime')?.value||0); let data={id:uid(),beanId:beanId||$('#logBean').value,method,grinderId:state.userProfile.grinders[0]?.id,grind:+$('#grind').value,dose:+$('#dose').value,rating:+$('#rating').value,flavours:$$('[data-flav].selected').map(x=>x.dataset.flav),notes:$('#notes').value,createdAt:iso()}; if(method==='Espresso')Object.assign(data,{yieldOut:+$('#yieldOut').value,time:elapsed||0}); else Object.assign(data,{water:+$('#water').value,totalTime:elapsed||0,bloom:+($('#bloom')?.value||0)}); state.brews.unshift(data); state.currentBeanId=data.beanId; stopTimer(false); toast('Brew saved'); go('home')}
function saveDialedProfile(beanId,method){let b=bean(beanId||$('#logBean').value); if(!b)return; let name=prompt('Profile name', 'Current')||'Current'; let arr=b.brewProfiles[method]=b.brewProfiles[method]||[]; if(name.toLowerCase()==='current')arr.forEach(p=>p.active=false); let p={id:uid(),name,active:name.toLowerCase()==='current',createdAt:iso(),score:+($('#rating')?.value||0),grinderId:state.userProfile.grinders[0]?.id,grind:+$('#grind').value,dose:+$('#dose').value,notes:$('#notes')?.value||''}; if(method==='Espresso')Object.assign(p,{yieldOut:+$('#yieldOut').value,time:timer.elapsed/1000||0,ratio:ratio({dose:+$('#dose').value,yieldOut:+$('#yieldOut').value})}); else Object.assign(p,{water:+$('#water').value,totalTime:timer.elapsed/1000||0,bloom:+($('#bloom')?.value||0)}); arr.push(p); toast('Dialed-in profile saved'); render()}
function brewUsingProfile(beanId,method,pid){closeModal(); selectedMethod=method; view='log'; setTimeout(()=>{render(); let p=(bean(beanId).brewProfiles[method]||[]).find(x=>x.id===pid); if(p){$('#logBean').value=beanId; $('#grind').value=(+p.grind).toFixed(1); syncRuler(+p.grind); $('#dose').value=p.dose||''; if(method==='Espresso')$('#yieldOut').value=p.yieldOut||''; else $('#water').value=p.water||'';}},0)}
function profileDetail(beanId,m,pid){let b=bean(beanId), p=(b.brewProfiles[m]||[]).find(x=>x.id===pid); modal(`<button class="edit-icon modal-edit" onclick="profileForm('${beanId}','${m}','${pid}')">${icon('pencil')}</button><h2>${esc(p.name)}</h2><div class="hero-detail"><b>${p.score||'—'}</b><span>Taste Score</span></div><div class="detail"><div><span>Method</span>${m}</div><div><span>Grind</span>${p.grind}</div><div><span>Dose</span>${p.dose}g</div><div><span>Output</span>${p.yieldOut||p.water||'—'}g</div><div><span>Time</span>${fmt(p.time||p.totalTime)}s</div><div><span>Notes</span>${esc(p.notes||'—')}</div></div><button class="btn full" onclick="brewUsingProfile('${beanId}','${m}','${pid}')">Brew Using This Profile</button>`)}
function profileForm(beanId,m,pid){let b=bean(beanId), p=pid?(b.brewProfiles[m]||[]).find(x=>x.id===pid):{}; modal(`<h2>${pid?'Edit':'New'} ${m} Profile</h2>${settingBlock(p.grind||18)}<label>Name</label><input id="pname" value="${esc(p.name||'Current')}"><div class="metric-grid"><label>Dose<input id="pdose" type="number" value="${p.dose||18}"></label><label>${m==='Espresso'?'Yield':'Water'}<input id="pout" type="number" value="${p.yieldOut||p.water||36}"></label></div><label>Time</label><input id="ptime" type="number" step="0.1" value="${p.time||p.totalTime||0}">${ratingBlock(p.score||7.5)}<label>Notes</label><textarea id="pnotes">${esc(p.notes||'')}</textarea><button class="btn full" onclick="saveRecipeProfile('${beanId}','${m}','${pid||''}')">Save Profile</button>`);bindRuler();updateRating(p.score||7.5)}
function saveRecipeProfile(beanId,m,pid){let b=bean(beanId), arr=b.brewProfiles[m]=b.brewProfiles[m]||[], old=arr.find(x=>x.id===pid), name=$('#pname').value||'Current'; let p={id:pid||uid(),name,active:name.toLowerCase()==='current',createdAt:old?.createdAt||iso(),score:+$('#rating').value,grinderId:state.userProfile.grinders[0]?.id,grind:+$('#grind').value,dose:+$('#pdose').value,notes:$('#pnotes').value}; if(p.active)arr.forEach(x=>x.active=false); if(m==='Espresso')Object.assign(p,{yieldOut:+$('#pout').value,time:+$('#ptime').value,ratio:ratio({dose:p.dose,yieldOut:+$('#pout').value})}); else Object.assign(p,{water:+$('#pout').value,totalTime:+$('#ptime').value}); if(old)Object.assign(old,p); else arr.push(p); closeModal(); openBeanDetail(beanId)}
function manageProfiles(id,m){modal(`<h2>Saved Profiles (${m})</h2>${(bean(id).brewProfiles[m]||[]).map(p=>`<div class="profile-list click" onclick="profileDetail('${id}','${m}','${p.id}')"><b>${esc(p.name)}</b><span>${p.score||'—'} Score</span><p>${p.grind} · ${dateShort(p.createdAt)}</p></div>`).join('')}<button class="btn full" onclick="profileForm('${id}','${m}')">Add New</button>`)}
function openBeanForm(id){let b=id?bean(id):{id:'',status:'current',name:'',roaster:'',origin:'',process:'',roastLevel:'Medium',roastDate:today(),photo:'',brewProfiles:{}}; modal(`<h2>${id?'Edit Bean':'New Bean'}</h2><div class="row"><button class="bag large ${b.photo?'has-photo':''}" onclick="pickPhoto('${id||'new'}')">${b.photo?`<img src="${b.photo}">`:'DF'}<em>${icon('camera')}</em></button><p>Add a photo of the bag.</p></div><label>Name</label><input id="bn" value="${esc(b.name)}"><label>Roaster</label><input id="br" value="${esc(b.roaster)}"><label>Origin</label><input id="bo" value="${esc(b.origin)}"><label>Process</label><input id="bp" value="${esc(b.process)}"><label>Roast Level</label><select id="bl"><option ${b.roastLevel==='Light'?'selected':''}>Light</option><option ${b.roastLevel==='Medium'?'selected':''}>Medium</option><option ${b.roastLevel==='Dark'?'selected':''}>Dark</option></select><label>Roast Date</label><input id="bd" type="date" value="${esc(b.roastDate)}"><label>Status</label><select id="bs"><option value="current" ${b.status==='current'?'selected':''}>Current</option><option value="archived" ${b.status==='archived'?'selected':''}>Archived</option></select><div class="action-gap"><button class="btn full" onclick="saveBean('${id||''}')">Save Bean</button></div><input type="file" id="photoInput" accept="image/*" hidden onchange="loadPhoto(event,'${id||'new'}')">`)}
function pickPhoto(id){$('#photoInput')?.click()} function loadPhoto(e,id){let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{if(id==='new')window.tempPhoto=r.result; else bean(id).photo=r.result; save(); render();}; r.readAsDataURL(f)}
function saveBean(id){let b={id:id||uid(),status:$('#bs').value,name:$('#bn').value,roaster:$('#br').value,origin:$('#bo').value,process:$('#bp').value,roastLevel:$('#bl').value,roastDate:$('#bd').value,photo:id?bean(id).photo:(window.tempPhoto||''),grinderId:state.userProfile.grinders[0]?.id,brewProfiles:id?bean(id).brewProfiles:{}}; if(id)Object.assign(bean(id),b); else state.beans.push(b); if(b.status==='current')state.currentBeanId=b.id; window.tempPhoto=''; closeModal(); render()}
function maintView(){let list=state.maintenance.filter(m=>maintTab==='other'?m.group==='other':m.group===maintTab); return `<section class="card"><h2>Maintenance</h2><div class="tabs"><button class="${maintTab==='grinder'?'sel':''}" onclick="maintTab='grinder';render()">Grinder</button><button class="${maintTab==='espresso'?'sel':''}" onclick="maintTab='espresso';render()">Espresso Machine</button></div>${list.map(maintRow).join('')||'<p>No items.</p>'}<button class="btn full secondary" onclick="editMaint()">Add Other Maintenance</button><section class="inner-card guide"><h3>Guides & Tips</h3><p>Use this area for DF Grinders maintenance links, videos, and cleaning tips.</p><a href="https://dfgrinders.ca/pages/manuals-guides" target="_blank">Open Manuals & Guides</a></section></section>`}
function maintRow(m){let d=new Date(m.lastDone); d.setDate(d.getDate()+Number(m.intervalDays)); let days=Math.ceil((d-new Date())/86400000); return `<div class="maint-row click" onclick="editMaint('${m.id}')"><div class="ico">${m.group==='grinder'?icon('maint'):brewSvg('Espresso')}</div><div><b>${esc(m.name)}</b><p>${esc(m.item)}<br>${days<=0?'Due now':'Due in '+days+' days'} · ${d.toLocaleDateString()}</p></div></div>`}
function editMaint(id){let m=id?state.maintenance.find(x=>x.id===id):{id:'',group:maintTab,name:'',item:'',intervalDays:7,lastDone:today()}; modal(`<h2>${id?'Edit':'Add Other'} Maintenance</h2><label>Type</label><select id="mg"><option value="grinder" ${m.group==='grinder'?'selected':''}>Grinder</option><option value="espresso" ${m.group==='espresso'?'selected':''}>Espresso Machine</option><option value="other" ${m.group==='other'?'selected':''}>Other</option></select><label>Name</label><input id="mn" value="${esc(m.name)}"><label>Item</label><input id="mi" value="${esc(m.item)}"><label>Frequency (days)</label><input id="mf" type="number" value="${esc(m.intervalDays)}"><label>Last done</label><input id="ml" type="date" value="${esc(m.lastDone)}"><button class="btn full" onclick="saveMaint('${id||''}')">Save</button>${id?`<button class="btn secondary full" onclick="doneMaint('${id}')">Mark Done Today</button>`:''}`)}
function saveMaint(id){let m={id:id||uid(),group:$('#mg').value,name:$('#mn').value,item:$('#mi').value,intervalDays:+$('#mf').value,lastDone:$('#ml').value}; if(id)Object.assign(state.maintenance.find(x=>x.id===id),m); else state.maintenance.push(m); closeModal(); render()} function doneMaint(id){state.maintenance.find(x=>x.id===id).lastDone=today();closeModal();render()}
function editProfile(){let p=state.userProfile,g=p.grinders[0]||{}; modal(`<h2>Edit Profile</h2><label>Brew Methods</label><div class="method-grid">${brewMethods.map(x=>`<button type="button" class="tile method ${p.brew.includes(x)?'selected':''}" data-brew="${x}" onclick="this.classList.toggle('selected')">${brewSvg(x)}<em>${x}</em></button>`).join('')}</div><h3>Espresso Machine</h3><label>Manufacturer</label><input id="pmake" value="${esc(p.machine.manufacturer)}"><label>Model</label><input id="pmodel" value="${esc(p.machine.model)}"><h3>Grinder</h3><label>Model</label><select id="gmodel">${models.map(m=>`<option ${g.model===m?'selected':''}>${m}</option>`).join('')}</select><label>Burr Type</label><select id="gburr" onchange="$('#gotherWrap').style.display=this.value==='Other'?'block':'none'"><option ${g.burrType==='Red Titanium'?'selected':''}>Red Titanium</option><option ${g.burrType==='Stainless Steel'?'selected':''}>Stainless Steel</option><option ${g.burrType==='Other'?'selected':''}>Other</option></select><div id="gotherWrap" style="display:${g.burrType==='Other'?'block':'none'}"><label>Other Burr</label><input id="gother" value="${esc(g.burrOther||'')}"></div><label>Burr Profile</label><select id="gprof"><option ${g.profile==='Brew'?'selected':''}>Brew</option><option ${g.profile==='Multipurpose (espresso)'?'selected':''}>Multipurpose (espresso)</option></select><label>Roast Preference</label><div class="roast-pref"><span>Light</span><span>Dark</span></div><input id="roastpref" class="roast-slider" type="range" min="0" max="100" value="${p.flavour.roast}"><label>Flavour Preferences</label><div class="select-grid">${['Chocolate','Fruity','Floral','Sweet','Funky'].map(x=>`<button class="tile ${p.flavour.notes.includes(x)?'selected':''}" data-pref="${x}" onclick="this.classList.toggle('selected')">${x}</button>`).join('')}</div><label>Workflow</label><div class="select-grid">${['Blind shaking','WDT','RDT','Slow feed','Distributor tool','Pre-infusion enabled'].map(x=>`<button class="tile ${p.workflow.includes(x)?'selected':''}" data-work="${x}" onclick="this.classList.toggle('selected')">${x}</button>`).join('')}</div><div class="action-gap"><button class="btn full" onclick="saveProfile()">Save Profile</button></div>`)}
function saveProfile(){let g=state.userProfile.grinders[0]||{id:uid()}; Object.assign(g,{model:$('#gmodel').value,name:$('#gmodel').value,burrType:$('#gburr').value,burrOther:$('#gburr').value==='Other'?$('#gother').value:'',profile:$('#gprof').value}); state.userProfile={brew:$$('[data-brew].selected').map(x=>x.dataset.brew),machine:{manufacturer:$('#pmake').value,model:$('#pmodel').value},grinders:[g],flavour:{roast:+$('#roastpref').value,notes:$$('[data-pref].selected').map(x=>x.dataset.pref)},workflow:$$('[data-work].selected').map(x=>x.dataset.work)}; closeModal(); render()}
function editBrew(id){let x=state.brews.find(b=>b.id===id); if(!x)return; closeModal(); selectedMethod=x.method; view='log'; render(); setTimeout(()=>{$('#logBean').value=x.beanId; $('#grind').value=x.grind; syncRuler(+x.grind); $('#dose').value=x.dose; if(x.method==='Espresso')$('#yieldOut').value=x.yieldOut; else $('#water').value=x.water; $('#notes').value=x.notes||''; $('#rating').value=x.rating||7.5; updateRating(x.rating||7.5)},20)}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal-bg"><div class="modal"><div class="modal-head"><span></span><button onclick="closeModal()">×</button></div>${html}</div></div>`); bind()}
function closeModal(){$('#modal')?.remove()} function filterBeans(q){q=q.toLowerCase(); let arch=beanTab==='archive'; $('#beanList').innerHTML=state.beans.filter(b=>(arch?b.status==='archived':b.status==='current')&&[b.name,b.roaster,b.origin,b.process].join(' ').toLowerCase().includes(q)).map(beanCard).join('')||'<p>No matches.</p>'}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='df-dial-backup.json';a.click()}
function toggleTimer(){h(18); if(timer.running){stopTimer(true);return} timer.running=true; timer.start=Date.now()-timer.elapsed; $('#timerCircle')?.classList.add('running'); $('#timerBtn')?.classList.add('stop'); $('#timeLabel').textContent='TAP TO STOP'; timer.int=setInterval(()=>{timer.elapsed=Date.now()-timer.start; let t=$('#timeText'); if(t)t.textContent=fmt(timer.elapsed/1000)},80)}
function stopTimer(keep=true){if(timer.int)clearInterval(timer.int); timer.int=null; timer.running=false; $('#timerCircle')?.classList.remove('running'); $('#timerBtn')?.classList.remove('stop'); if($('#timeLabel'))$('#timeLabel').textContent='TAP TO START'; if(!keep){timer.elapsed=0;if($('#timeText'))$('#timeText').textContent='00.0'}}
function bindRuler(){let r=$('#ruler'), track=$('#track'), input=$('#grind'); if(!r||!track||!input)return; let min=0,max=100,step=.1,pxPer=.9; track.innerHTML=''; for(let i=min;i<=max;i++){let major=i%5===0, mid=i%1===0; let m=document.createElement('div'); m.className='mark '+(major?'major':mid?'whole':''); m.style.minWidth=(pxPer*10)+'px'; if(major)m.innerHTML=`<span>${i}</span>`; track.appendChild(m)} function pos(v){track.style.transform=`translateX(${r.clientWidth/2 - (v-min)*10*pxPer}px)`} window.syncRuler=v=>{v=Math.max(min,Math.min(max,Math.round(v*10)/10)); input.value=v.toFixed(1); pos(v)}; syncRuler(+input.value||0); let dragging=false,last=0,startVal=0,lastH=0; r.onpointerdown=e=>{dragging=true;last=e.clientX;startVal=+input.value||0;r.setPointerCapture(e.pointerId)}; r.onpointermove=e=>{if(!dragging)return; let dx=e.clientX-last, v=startVal - dx/(10*pxPer); let nv=Math.max(min,Math.min(max,Math.round(v*10)/10)); if(Math.floor(nv)!==lastH){h(4);lastH=Math.floor(nv)} syncRuler(nv)}; r.onpointerup=e=>{dragging=false;h(8)} }
function bind(){bindRuler();updateRating($('#rating')?.value||7.5)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js'); render();
