const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const nowISO=()=>new Date().toISOString(), today=()=>new Date().toISOString().slice(0,10);
const storeKey='dfDialV6';
const models=['DF54 V4','DF54 V3','DF64 Gen 2','DF64V','DF83','DF83V','DC63','Other'];
const origins=['Brazil','Colombia','Ethiopia','Guatemala','Costa Rica','Honduras','Kenya','Rwanda','Peru','Mexico','Panama','El Salvador'];
let view='home', state=load(), timer={start:null,elapsed:0,int:null};
function load(){const s=localStorage.getItem(storeKey); if(s) return JSON.parse(s); const g=uid(), b1=uid(), b2=uid(), b3=uid(); const t=nowISO(); return {theme:'dark',currentBeanId:b1,grinders:[{id:g,name:'DF64 Gen 2',model:'DF64 Gen 2',burrs:'Stock stainless'}],espressoMachine:'Espresso machine',beans:[{id:b1,status:'active',name:'Ethiopia Chelbesa',roaster:'Konga',origin:'Ethiopia',process:'Washed',roastLevel:'Light',roastDate:'2026-05-24',grinderId:g,createdAt:t,updatedAt:t},{id:b2,status:'active',name:'Colombia Los Naranjos',roaster:'Onyx Coffee Lab',origin:'Colombia',process:'Washed',roastLevel:'Medium',roastDate:'2026-05-20',grinderId:g,createdAt:t,updatedAt:t},{id:b3,status:'active',name:'Brazil Fazenda',roaster:'DF Coffee Co.',origin:'Brazil',process:'Natural',roastLevel:'Dark',roastDate:'2026-05-18',grinderId:g,createdAt:t,updatedAt:t}],shots:[{id:uid(),beanId:b1,grinderId:g,grind:'18.6',dose:'18.0',yieldOut:'36.2',time:'29.0',rating:'Good',createdAt:t},{id:uid(),beanId:b2,grinderId:g,grind:'17.8',dose:'18.0',yieldOut:'36.0',time:'32.0',rating:'Good',createdAt:t}],maintenance:[{id:uid(),type:'Grinder burr cleaning',item:'DF64 Gen 2',intervalDays:30,lastDone:today()},{id:uid(),type:'Full burr deep clean',item:'DF64 Gen 2',intervalDays:60,lastDone:today()},{id:uid(),type:'Declumper check',item:'DF64 Gen 2',intervalDays:30,lastDone:today()},{id:uid(),type:'Espresso machine cleaning',item:'Espresso machine',intervalDays:7,lastDone:today()}],roasters:['Archive Coffee','Konga','Onyx Coffee Lab','Black & White Coffee Roasters'].map(name=>({id:uid(),name,aliases:[norm(name)]}))}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));document.documentElement.dataset.theme=state.theme}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1800)}
function haptic(ms=12){try{navigator.vibrate&&navigator.vibrate(ms)}catch(e){}}
function norm(s){return (s||'').toLowerCase().replace(/coffee|roasters|roaster|co\.?|company|inc|ltd|the/g,'').replace(/[^a-z0-9]/g,'').trim()}
function lev(a,b){const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length]}
function canonicalRoaster(input){const c=norm(input); if(!c) return input; let best=null,score=99; state.roasters.forEach(r=>(r.aliases||[norm(r.name)]).forEach(a=>{const d=lev(c,a); if(d<score){score=d;best=r}})); if(best&&(score<=2||c.includes(norm(best.name))||norm(best.name).includes(c))){if(input.length>best.name.length) best.name=input; if(!best.aliases.includes(c))best.aliases.push(c);return best.name} state.roasters.push({id:uid(),name:input,aliases:[c]}); return input}
const bean=id=>state.beans.find(b=>b.id===id), grinder=id=>state.grinders.find(g=>g.id===id)||state.grinders[0]||{};
const shotsFor=id=>state.shots.filter(s=>s.beanId===id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
const lastShot=id=>shotsFor(id)[0];
const currentBean=()=>bean(state.currentBeanId)||state.beans.find(b=>b.status!=='archived')||state.beans[0];
function dueInfo(){let soon=null; state.maintenance.forEach(m=>{const d=new Date(m.lastDone);d.setDate(d.getDate()+Number(m.intervalDays)); if(!soon||d<soon.date) soon={m,date:d}}); const days=soon?Math.ceil((soon.date-new Date())/86400000):0; return {soon,days}}
function ratio(s){const d=parseFloat(s.dose), y=parseFloat(s.yieldOut); return d&&y?'1:'+(y/d).toFixed(1):'—'}
function timeFmt(sec){sec=Number(sec||0); if(sec<60)return sec.toFixed(1).padStart(4,'0'); const m=Math.floor(sec/60), r=(sec%60).toFixed(1).padStart(4,'0'); return `${m}:${r}`}
function header(){return `<section class="hero"><img class="wordmark" src="dfgrinderslogo.png" alt="DF Grinders"></section>`}
function nav(){const items=[['home','⌂','Home'],['beans','◒','Beans'],['shot','+','Log shot'],['maintenance','🔧','Maintenance'],['more','☰','More']];return `<nav class="tabs">${items.map(([id,ic,lab])=>`<button class="tab ${view===id?'active':''}" onclick="haptic();go('${id}')" aria-label="${lab}">${ic}</button>`).join('')}</nav>`}
function go(v){view=v; render()}
function render(){save(); $('#app').innerHTML=header()+({home:homeView,beans:beansView,shot:shotView,maintenance:maintenanceView,more:settingsView,history:historyView,archive:archiveView,activeBeans:activeBeansView}[view]||homeView)()+nav(); bindSuggests();}
function homeView(){const b=currentBean(), ls=b?lastShot(b.id):null, g=ls?grinder(ls.grinderId):grinder(b?.grinderId), month=new Date().toISOString().slice(0,7), shotsMonth=state.shots.filter(s=>s.createdAt.slice(0,7)===month).length, active=state.beans.filter(b=>b.status!=='archived').length, d=dueInfo();return `<div class="grid"><section class="card current" onclick="openSummary('${b?.id||''}')"><h2>Current Bean</h2><div class="bean-line"><div class="bag">DF</div><div><b>${esc(b?.name||'No bean selected')}</b><p>${esc(b?.roaster||'')}<br>${esc([b?.origin,b?.process].filter(Boolean).join(' • '))}</p></div><span class="roast-pill">${esc(b?.roastLevel||'')}</span></div></section><section class="card current" onclick="openSummary('${b?.id||''}')"><h2>Last Used Settings</h2><div class="setting-summary"><div><span>Grinder</span><b>${esc(g?.name||'—')}</b><small>${esc(g?.burrs||'')}</small></div><div class="giant">${esc(ls?.grind||'—')}</div></div><div class="setting-chips"><span>Dose <b>${esc(ls?.dose||'—')}g</b></span><span>Yield <b>${esc(ls?.yieldOut||'—')}g</b></span><span>Ratio <b>${ls?ratio(ls):'—'}</b></span><span>Time <b>${ls?timeFmt(ls.time):'—'}s</b></span></div></section><div class="stat-row"><button class="stat" onclick="go('activeBeans')"><span>Active Beans</span><b>${active}</b></button><button class="stat" onclick="go('history')"><span>Shots This Month</span><b>${shotsMonth}</b></button><button class="stat" onclick="go('maintenance')"><span>Maintenance Due</span><b>${d.days<=0?'Now':d.days+'d'}</b></button></div><section class="card"><h2>Shot History</h2><div class="list">${state.shots.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,3).map(shotRow).join('')||'<p class="small">No shots yet.</p>'}</div></section></div>`}
function beanCard(b){const s=lastShot(b.id);return `<div class="bean-card card" onclick="haptic();openBean('${b.id}')"><div class="bean-main"><div class="bag">DF</div><div><div class="bean-title">${esc(b.name)}</div><div class="meta">${esc(b.roaster||'')}<br>${esc(b.origin||'')} · ${s?esc(s.grind)+' setting':'No shots yet'}</div></div><span class="roast-pill">${esc(b.roastLevel||'')}</span></div></div>`}
function beansView(){return `<section class="card"><h2>Beans</h2><input placeholder="Search beans or roasters" oninput="filterBeans(this.value)"><div class="actions"><button class="chip" onclick="go('activeBeans')">Active</button><button class="chip" onclick="go('archive')">Archive</button><button class="chip" onclick="openBean()">New Bean</button></div><div id="beanList" class="list">${state.beans.filter(b=>b.status!=='archived').map(beanCard).join('')||'<p class="small">No active beans.</p>'}</div></section>`}
function activeBeansView(){return `<section class="card"><h2>Active Beans</h2><input placeholder="Search active beans" oninput="filterBeans(this.value,false)"><div class="list" id="beanList">${state.beans.filter(b=>b.status!=='archived').map(beanCard).join('')}</div></section>`}
function archiveView(){return `<section class="card"><h2>Bean Archive</h2><p class="small">Search old beans to recover previous grind settings when you buy the same coffee again.</p><input placeholder="Search archived beans" oninput="filterBeans(this.value,true)"><div class="list" id="beanList">${state.beans.filter(b=>b.status==='archived').map(beanCard).join('')||'<p class="small">No archived beans yet.</p>'}</div></section>`}
function historyView(){const shots=state.shots.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,20);return `<section class="card"><h2>Last 20 Shots</h2><div class="list">${shots.map(shotRow).join('')||'<p class="small">No shots yet.</p>'}</div></section>`}
function shotRow(s){const b=bean(s.beanId);return `<div class="shot-row card" onclick="openShot('${s.beanId}','${s.id}')"><b>${esc(b?.name||'Unknown bean')}</b><span>${esc(s.grind||'—')}</span><p>${esc(grinder(s.grinderId)?.name||'')} · ${esc(s.dose||'—')}g → ${esc(s.yieldOut||'—')}g · ${ratio(s)} · ${timeFmt(s.time)}s</p><small>${new Date(s.createdAt).toLocaleString()}</small></div>`}
function shotView(){return `<section class="card"><h2>Log Shot</h2>${shotForm()}</section>`}
function shotForm(beanId='',shotId=''){const sh=state.shots.find(s=>s.id===shotId)||{}, b=bean(beanId||sh.beanId)||currentBean()||{}, last=lastShot(b.id)||{}, val=Number(sh.grind||last.grind||15); const opts=`<option value="">Create new bean…</option>`+state.beans.filter(x=>x.status!=='archived').map(x=>`<option value="${x.id}" ${x.id===b.id?'selected':''}>${esc(x.name)} — ${esc(x.roaster||'')}</option>`).join('');return `<div class="seg"><button class="${b.id?'active':''}" type="button">Existing Bean</button><button type="button" onclick="$('#shotBean').value='';shotBeanChanged('')">New Bean</button></div><div class="form-card"><label>Bean</label><select id="shotBean" onchange="shotBeanChanged(this.value)">${opts}</select><div id="newBeanMini" style="display:none"><label>New bean name</label><input id="miniBeanName" placeholder="Brazil Natural"><label>Roaster</label><div class="suggestions"><input id="miniRoaster" data-suggest="roaster" placeholder="Archive Coffee"></div></div></div><div class="form-card setting-card"><div><label>Grinder</label><b>${esc(grinder(sh.grinderId||b.grinderId)?.name||'DF Grinder')}</b><div class="inline-ruler" id="shotRuler" data-value="${val.toFixed(1)}"></div></div><div><label>Setting</label><input id="shotGrind" inputmode="decimal" value="${val.toFixed(1)}" oninput="setRulerValue($('#shotRuler'),this.value)" class="setting-input"></div></div><div class="shot-grid"><div class="form-card"><label>Dose</label><input id="shotDose" inputmode="decimal" value="${esc(sh.dose||last.dose||18)}"></div><div class="form-card"><label>Yield</label><input id="shotYield" inputmode="decimal" value="${esc(sh.yieldOut||last.yieldOut||36)}"></div></div><input id="shotTime" type="hidden" value="${esc(sh.time||'')}"><div class="timer-wrap" id="timerWrap" onclick="timerToggle()"><div class="timer-inner"><div><div class="timer-time" id="timerDisplay">${timeFmt(sh.time||0)}</div><div class="timer-label" id="timerLabel">TAP TO START</div></div></div></div><div class="timer-actions"><button class="btn secondary" onclick="timerReset();event.stopPropagation()">Reset</button><button id="timerButton" class="btn big-play" onclick="timerToggle();event.stopPropagation()">Start/Stop</button></div><div class="form-card"><label>Taste / Result</label><select id="shotRating"><option></option><option ${sh.rating==='Good'?'selected':''}>Good</option><option ${sh.rating==='Too fast / sour'?'selected':''}>Too fast / sour</option><option ${sh.rating==='Too slow / bitter'?'selected':''}>Too slow / bitter</option><option ${sh.rating==='Thin'?'selected':''}>Thin</option><option ${sh.rating==='Harsh'?'selected':''}>Harsh</option></select><label>Notes</label><textarea id="shotTaste">${esc(sh.taste||'')}</textarea></div><button class="btn full" onclick="saveShot('${shotId}')">Save shot</button></div>`}
function initRuler(el){if(!el||el.dataset.ready)return;el.dataset.ready=1; drawRuler(el,Number(el.dataset.value||15)); let startX=0,startVal=0,lastWhole=Math.round(Number(el.dataset.value||15)); el.addEventListener('pointerdown',e=>{haptic(8);el.setPointerCapture(e.pointerId);startX=e.clientX;startVal=Number(el.dataset.value||15);el.classList.add('press')}); el.addEventListener('pointermove',e=>{if(!el.classList.contains('press'))return; const v=Math.max(0,Math.min(40,startVal+(e.clientX-startX)/28)); setRulerValue(el,v); const w=Math.round(v); if(w!==lastWhole){lastWhole=w; haptic(5)}}); ['pointerup','pointercancel','lostpointercapture'].forEach(ev=>el.addEventListener(ev,()=>el.classList.remove('press')))}
function drawRuler(el,val){let html=''; const start=Math.floor((val-6)/5)*5, end=start+15; for(let i=start;i<=end;i++){html+=`<div class="mark major"><span>${i}</span></div>`; if(i<end) for(let j=1;j<5;j++) html+=`<div class="mark minor"></div>`} el.innerHTML=`<div class="ruler-track" style="transform:translateX(${-(val-start)*28}px)">${html}</div><div class="ruler-center"></div>`}
function setRulerValue(el,v){v=Number(v); if(!isFinite(v))return; v=Math.round(v*10)/10; el.dataset.value=v.toFixed(1); const inp=$('#shotGrind'); if(inp&&document.activeElement!==inp) inp.value=v.toFixed(1); drawRuler(el,v)}
function shotBeanChanged(id){const b=bean(id); if(!b){$('#newBeanMini').style.display='block';return} closeModal(); openShot(id)}
function suggest(s){const t=parseFloat(s.time), r=s.rating||''; if(r.includes('fast')||t<25)return 'Suggestion: grind finer by 0.2–0.4.'; if(r.includes('slow')||t>35)return 'Suggestion: grind coarser by 0.2–0.4.'; if(r==='Good')return 'Suggestion: keep this as the reference setting.'; return 'Suggestion: compare taste and shot time before changing.'}
function saveShot(id=''){let beanId=$('#shotBean')?.value; if(!beanId){const g=state.grinders[0]?.id; const b={id:uid(),status:'active',name:$('#miniBeanName')?.value||'Unnamed bean',roaster:canonicalRoaster($('#miniRoaster')?.value||''),origin:'',process:'',roastLevel:'Medium',roastDate:today(),grinderId:g,createdAt:nowISO(),updatedAt:nowISO()}; state.beans.push(b); beanId=b.id} const old=state.shots.find(x=>x.id===id), data={beanId,grinderId:bean(beanId)?.grinderId||state.grinders[0]?.id,grind:$('#shotGrind').value,dose:$('#shotDose').value,yieldOut:$('#shotYield').value,time:$('#shotTime').value||String((timer.elapsed/1000).toFixed(1)),rating:$('#shotRating').value,taste:$('#shotTaste').value,updatedAt:nowISO()}; data.suggestion=suggest(data); if(old)Object.assign(old,data); else state.shots.push({id:uid(),...data,createdAt:nowISO()}); state.currentBeanId=beanId; bean(beanId).updatedAt=nowISO(); closeModal(); view='home'; render(); toast('Shot saved')}
function openShot(beanId='',shotId=''){showModal(`<div class="modal-titlebar"><button onclick="closeModal()">×</button><h2>${shotId?'Edit Shot':'Log Shot'}</h2><button onclick="saveShot('${shotId}')">✓</button></div>${shotForm(beanId,shotId)}`); bindSuggests(); initRuler($('#shotRuler')); updateTimerUI()}
function openBean(id=''){const b=bean(id)||{}, shots=shotsFor(id); showModal(`<div class="modal-titlebar"><button onclick="closeModal()">×</button><h2>${id?'Bean Profile':'New Bean'}</h2><button onclick="saveBean('${id}')">✓</button></div><div class="profile-head"><div class="profile-bag">DF</div><div><h2>${esc(b.name||'New Bean')}</h2><p class="meta">${esc(b.roaster||'')}</p></div></div><div class="form-card"><label>Name</label><input id="beanName" value="${esc(b.name||'')}"><label>Roaster</label><div class="suggestions"><input id="beanRoaster" data-suggest="roaster" value="${esc(b.roaster||'')}"></div><label>Origin</label><div class="suggestions"><input id="beanOrigin" data-suggest="origin" value="${esc(b.origin||'')}"></div><label>Process</label><input id="beanProcess" value="${esc(b.process||'')}"><label>Roast Date</label><input id="beanRoastDate" type="date" value="${esc(b.roastDate||today())}"><label>Roast Level</label><select id="beanRoastLevel"><option ${b.roastLevel==='Light'?'selected':''}>Light</option><option ${b.roastLevel==='Medium'?'selected':''}>Medium</option><option ${b.roastLevel==='Dark'?'selected':''}>Dark</option></select><label>Status</label><select id="beanStatus"><option value="active" ${b.status!=='archived'?'selected':''}>Currently Active</option><option value="archived" ${b.status==='archived'?'selected':''}>Archived</option></select></div>${id?`<div class="form-card"><h3>Last 20 Shots</h3><div class="list">${shots.slice(0,20).map(shotRow).join('')||'<p class="small">No shots yet.</p>'}</div></div>`:''}<button class="btn full" onclick="saveBean('${id}')">Save Bean</button>${id?`<button class="btn secondary full" onclick="archiveBean('${id}')">${b.status==='archived'?'Reactivate':'Archive'} Bean</button>`:''}`); bindSuggests()}
function saveBean(id=''){const data={name:$('#beanName').value,roaster:canonicalRoaster($('#beanRoaster').value),origin:$('#beanOrigin').value,process:$('#beanProcess').value,roastDate:$('#beanRoastDate').value,roastLevel:$('#beanRoastLevel').value,status:$('#beanStatus').value,updatedAt:nowISO(),grinderId:state.grinders[0]?.id}; if(id)Object.assign(bean(id),data); else state.beans.push({id:uid(),...data,createdAt:nowISO()}); closeModal(); render(); toast('Bean saved')}
function archiveBean(id){const b=bean(id); b.status=b.status==='archived'?'active':'archived'; closeModal(); render();}
function openSummary(id){const b=bean(id); if(!b)return; const s=lastShot(id)||{}, g=grinder(s.grinderId||b.grinderId), shots=shotsFor(id), avg=shots.length?(shots.reduce((a,x)=>a+Number(x.time||0),0)/shots.length).toFixed(1):'—', d=dueInfo(); showModal(`<div class="modal-titlebar"><button onclick="closeModal()">×</button><h2>Current Bean</h2><button onclick="openBean('${id}')">Edit</button></div><div class="profile-head"><div class="profile-bag">DF</div><div><h2>${esc(b.name)}</h2><p>${esc(b.roaster)}<br>${esc([b.origin,b.process,b.roastLevel].filter(Boolean).join(' • '))}</p></div></div><div class="detail-list"><div class="detail-row"><span>Grinder</span><b>${esc(g.name||'—')}</b></div><div class="detail-row"><span>Burrs</span><b>${esc(g.burrs||'—')}</b></div><div class="detail-row"><span>Machine</span><b>${esc(state.espressoMachine||'—')}</b></div><div class="detail-row"><span>Setting</span><b>${esc(s.grind||'—')}</b></div><div class="detail-row"><span>Dose/Yield</span><b>${esc(s.dose||'—')}g / ${esc(s.yieldOut||'—')}g</b></div><div class="detail-row"><span>Ratio/Time</span><b>${s.beanId?ratio(s):'—'} / ${s.beanId?timeFmt(s.time)+'s':'—'}</b></div><div class="detail-row"><span>Total Shots</span><b>${shots.length}</b></div><div class="detail-row"><span>Average Time</span><b>${avg}${avg==='—'?'':'s'}</b></div><div class="detail-row"><span>Next Maint.</span><b>${d.soon?esc(d.soon.m.type)+' · '+(d.days<=0?'Due now':d.days+' days'):'—'}</b></div></div>`)}
function maintenanceView(){return `<section class="card"><h2>Maintenance</h2><div class="seg"><button class="active">Grinder</button><button>Espresso Machine</button></div><div class="list">${state.maintenance.map(m=>{const d=new Date(m.lastDone);d.setDate(d.getDate()+Number(m.intervalDays));const days=Math.ceil((d-new Date())/86400000);return `<div class="maint card"><div class="maint-ico">⚙</div><div><b>${esc(m.type)}</b><p>${esc(m.item)}<br>${days<=0?'Due now':'Due in '+days+' days'} · ${d.toLocaleDateString()}</p></div><button class="chip" onclick="doneMaint('${m.id}')">Done</button></div>`}).join('')}</div></section>`}
function doneMaint(id){state.maintenance.find(m=>m.id===id).lastDone=today();render();toast('Maintenance reset')}
function settingsView(){return `<section class="card"><h2>More</h2><label>Theme</label><select onchange="state.theme=this.value;render()"><option value="dark" ${state.theme==='dark'?'selected':''}>Dark</option><option value="light" ${state.theme==='light'?'selected':''}>Light</option></select><label>Espresso Machine</label><input value="${esc(state.espressoMachine||'')}" onchange="state.espressoMachine=this.value;save()"><h3>Grinder</h3>${state.grinders.map(g=>`<div class="card"><b>${esc(g.name)}</b><p>${esc(g.burrs||'')}</p></div>`).join('')}<button class="btn secondary full" onclick="editGrinder()">Edit grinder</button><button class="btn secondary full" onclick="exportData()">Export backup JSON</button><label>Import backup</label><input type="file" accept="application/json" onchange="importData(this.files[0])"></section>`}
function editGrinder(){const g=state.grinders[0]||{};showModal(`<div class="modal-titlebar"><button onclick="closeModal()">×</button><h2>Grinder</h2><button onclick="saveGrinder()">✓</button></div><label>Name</label><input id="gName" value="${esc(g.name||'')}"><label>Model</label><select id="gModel">${models.map(m=>`<option ${g.model===m?'selected':''}>${m}</option>`).join('')}</select><label>Burrs</label><input id="gBurrs" value="${esc(g.burrs||'')}"><button class="btn full" onclick="saveGrinder()">Save</button>`)}
function saveGrinder(){state.grinders[0]=Object.assign(state.grinders[0]||{id:uid()},{name:$('#gName').value,model:$('#gModel').value,burrs:$('#gBurrs').value});closeModal();render()}
function bindSuggests(){$$('[data-suggest]').forEach(inp=>{inp.oninput=()=>{const arr=inp.dataset.suggest==='origin'?origins:state.roasters.map(r=>r.name), q=inp.value.toLowerCase(); let old=inp.parentElement.querySelector('.suggest-box'); old&&old.remove(); if(!q)return; const m=arr.filter(x=>x.toLowerCase().includes(q)).slice(0,6); if(!m.length)return; const box=document.createElement('div'); box.className='suggest-box'; box.innerHTML=m.map(x=>`<button type="button">${esc(x)}</button>`).join(''); inp.parentElement.appendChild(box); $$('button',box).forEach(b=>b.onclick=()=>{inp.value=b.textContent;box.remove()})}}); $$('.inline-ruler').forEach(initRuler)}
function filterBeans(q='',archived=false){q=q.toLowerCase(); const list=state.beans.filter(b=>(archived?b.status==='archived':b.status!=='archived')&&[b.name,b.roaster,b.origin,b.process,b.roastLevel].join(' ').toLowerCase().includes(q)); $('#beanList').innerHTML=list.map(beanCard).join('')||'<p class="small">No matches.</p>'}
function updateTimerUI(){const sec=timer.elapsed/1000; const d=$('#timerDisplay'); if(d)d.textContent=timeFmt(sec); const running=!!timer.int; $('#timerWrap')?.classList.toggle('running',running); $('#timerButton')?.classList.toggle('running',running); const lab=$('#timerLabel'); if(lab)lab.textContent=running?'TAP TO STOP':'TAP TO START'}
function timerToggle(){haptic(18); if(timer.int)timerStop();else timerStart()}
function timerStart(){if(timer.int)return; timer.start=Date.now()-timer.elapsed; timer.int=setInterval(()=>{timer.elapsed=Date.now()-timer.start;updateTimerUI()},40); updateTimerUI()}
function timerStop(){clearInterval(timer.int);timer.int=null;$('#shotTime')&&($('#shotTime').value=(timer.elapsed/1000).toFixed(1));updateTimerUI()}
function timerReset(){clearInterval(timer.int);timer={start:null,elapsed:0,int:null};$('#shotTime')&&($('#shotTime').value='');updateTimerUI(); const d=$('#timerDisplay'); if(d)d.textContent='00.0'}
function showModal(html){closeModal();const b=document.createElement('div');b.id='modal';b.className='modal-backdrop';b.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(b)}
function closeModal(){$('#modal')?.remove();timerReset()}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='df-dial-backup.json';a.click()}
function importData(f){if(!f)return;const r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();render()};r.readAsText(f)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');document.documentElement.dataset.theme=state.theme;render();
